language: python
python:
  - "3.7"
cache: pip
install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)