language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install pipenv
  - pipenv install
  - pipenv install coverage
script:
  - pipenv run coverage run pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)